### ISSUE TITLE
[mediator/client] config file

### ISSUE THREAD

**Issue by dolow** [drecom/scene-graph#23]
Environment variable is the only way to pass configurable value to module currently.
This can be described as static config file and should be managed as a part of project.
Config file may look like this;

```
const animationCli = require('@drecom/scene-graph-cocos-animation-cli');

module.exports = () => {
  return {
    runtime: 'cc2',
    assetRoot: '/path/to/assets',
    dest: '/path/to/dest',
    sceneFiles: [
      '/path/to/assets/scenes/scene1.fire',
      '/path/to/assets/scenes/scene2.fire'
    ],
    plugins: [
      animationCli
    ]
  };
}
```

**Comment by Egliss** [comment]
The module ParseArgs combines current directory and the input path(config file's "assetRoot").
so the path will be broken when the config file is specified from another directory.

1. Do not allow directory information when entering configuration file (allow only file name input)
2. Modify ParseArgs module (is there a problem as javascript ?)

**Comment by dolow** [comment]
@Egliss

I think this should be done as below;

__Paths as CLI argument;__
User's current working directly should be base directly.
e.g) `path.resolve(process.cwd(), assetPath)`

__Paths as configFile;__
Directory of config file should be base directory.
e.g) `path.resolve(path.dirname(configFilePath), assetPath})`

I understand that combination of config file and CLI argument makes thing complicated.
It can be consider later.
